export function crearPvEstadoPayload({
  selectModulo,
  select_economico,
  motivos_select,
  credencial,
  turno,
  eco_de,
  no_extintor,
  modalidadSelect,
  rutaSelect,
  cc,
  entrada_operador,
}: any) {
  return {
    tipo: 1,
    eco: select_economico,
    eco_estatus: 1,
    eco_tipo: 1,
    motivo_id: motivos_select?.id,
    motivo_desc: motivos_select?.desc,
    modulo: selectModulo,
    direccion: "Dirección ejemplo",
    ruta: rutaSelect?.ruta_origen_cve || "Ruta ejemplo",
    ruta_modalidad: modalidadSelect || "Modalidad ejemplo",
    ruta_cc: cc,
    op_cred: credencial,
    op_turno: turno,
    extintor: no_extintor,
    estatus: 1,
    modulo_puerta: "Puerta ejemplo",
    momento: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    createdBy: 1,
    createdBy_modulo: 1,
  };
}
